# Q2 Submatrix Determinant

In [2]:
# Q2: Sub-matrix and Determinant
import numpy as np

A = np.arange(1,17).reshape(4,4)
sub = A[2:4, 0:2]

print("Matrix:\n", A)
print("Sub-matrix:\n", sub)
print("Determinant:", np.linalg.det(sub))

Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Sub-matrix:
 [[ 9 10]
 [13 14]]
Determinant: -4.0000000000000036
